name: MGM
favicon: null
layout_spectrum: 0.54501
typography_spectrum: 0.6276719670277089
title: Michael Marcusa - Social Researcher
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#cac84f'
    - '#97973b'
    - '#626019'
    - '#fbfbfb'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
