name: MGM
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6276719670277089
title: Michael Marcusa - Social Researcher
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aab480'
    - '#7b6b54'
    - '#4d1a29'
    - '#eefe9b'
    - '#d1982f'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
