name: MGM
favicon: null
layout_spectrum: 0.24168
typography_spectrum: 0.6276719670277089
title: 'Michael Marcusa - Social Researcher | Cultural Translator | Political Analyst'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#18221a'
    - '#e5fde5'
    - '#be9b71'
    - '#569283'
    - '#89cfac'
  brandStrength: 0
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
