name: MGM
favicon: null
layout_spectrum: 0.1994188972748816
typography_spectrum: 0.6276719670277089
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9501618451904505
  lightness: 0.36881182296201587
  saturation: 0.8143272576853633
  rhythmicContrast: 0.21526911202818155
purpose: []
